# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Altalabs add-on
version: "1.0.0"
slug: altalabs
description: altalabs add-on
url: "https://github.com/Svellem/hassio-addons-altalabs/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Alta Labs cntrl"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
