# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Altalabs add-on
version: "1.0.0"
slug: altalabs
description: altalabs add-on
url: "https://github.com/Svellem/hassio-addons-altalabs/main/example"
arch:
  - amd64
init: false
map:
  - share:rw
options:
  message: "Alta Labs cntrl"
schema:
  message: "str?"
image: "https://hub.docker.com/r/altalabs/control/1.1e-amd64"
